### ISSUE TITLE
Where do I get duplicati-*.zip from? 

### ISSUE THREAD

**Issue by Nornode** [cyrilpawelko/duplicati#2]
Hello, 

Thank you for keeping this public!
I recently got hold of an old Asustor NAS (AS-302T).
I found your APK available in the store which led me here. 

As I was trying to make an updated package, I couldn't understand where you'd get the duplicati* zip from.
Can you please tell me or, add instructions to the bash script please?

I hope I can create an upstream PR you can merge. (see fork)
Many thanks for your help!

**Comment by cyrilpawelko** [comment]
Hello,

You can download the zip file from https://www.duplicati.com/download
I updated the build.sh file
I let you fork, I don't maintain this script anymore.

PS 1 : once the package is build, you can use the integrated updater within duplicati, withtout having to build a new asustor package
PS 2 : another (and more recent) [package ](https://www.asustor.com/app_central/app_detail?id=1446&type=20&model=)was built by someone else.

**Comment by Nornode** [comment]
Thank you! 
I managed to build the package myself, undortunately the package you linked to does not support my old model.
Unfortunately I had to adjust your build scripe a lot since it seems to be specific to your environment. 
I built mine on MacOS ARM version which might have caused the script errors. 
Anyway, it worked like a charm after those where solved, thanks again!
